# Generated by Django 4.1.7 on 2023-02-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topic_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
