# Generated by Django 4.1.7 on 2023-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Ridelink Series', max_length=200),
        ),
    ]
