# Generated by Django 4.1.7 on 2023-02-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_created']},
        ),
    ]
